Parent class instance blocks


Example 1:


class Parent1
{
	{
		System.out.println("Parent class instance blocks");
		}
		Parent1()
		{
		System.out.println("Parent class 0-arg constructor");
		}
		static{
		System.out.println("Parent class Static Block");
		}
	
}
class ParentInstanceBlock extends Parent1
{
	{
		System.out.println("Child class instance blocks");
		}
	ParentInstanceBlock()
		{
		//super(); code is generated by compiler
		System.out.println("Child class 0-arg constructor");
		}
		public static void main(String... args)
		{
			new ParentInstanceBlock();
		}
}
