Parent class Static blocks

class Parent {
{
System.out.println("Parent class instance blocks");
}
Parent()
{
System.out.println("Parent class 0-arg constructor");
}
static{
System.out.println("Parent class static block");
}
class Child
{
{
System.out.println("Child class instance blocks");
}
Child()
{
//super(); code is generated by compiler
System.out.println("Child class 0-arg constructor");
}
static{
System.out.println("Child class static block");
}
	public static void main(String[] args)
	{
	new Child();
	new Child();
	{
}